[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Broombots Software Learning Resources"
authors = [{name = "Tobin Rumsey", email = "broombots@broomfieldstem.org"}]
dynamic = ["version", "description"]
